spring.application.name=Church-Management-System

spring.datasource.url=jdbc:mysql://localhost:3306/church_management
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ==========================================
# MTN MoMo Configuration
# ==========================================

mtn.momo.base-url=https://sandbox.momodeveloper.mtn.com

mtn.momo.subscription-key=${MTN_SUBSCRIPTION_KEY:NOT_CONFIGURED}
mtn.momo.api-user=${MTN_API_USER:NOT_CONFIGURED}
mtn.momo.api-key=${MTN_API_KEY:NOT_CONFIGURED}
mtn.momo.callback-url=${MTN_CALLBACK_URL:http://localhost:8080/api/momo/callback}